# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MillenniumStarERP' do
     pod 'AFNetworking’
     pod 'SDWebImage'
     pod 'MJExtension'
     pod 'SVProgressHUD'
     pod 'MJRefresh'
     pod 'MWPhotoBrowser'
     pod 'Masonry'
     pod 'JPush'
end

target 'MillenniumStarERPTests' do

end

target 'MillenniumStarERPUITests' do

end

